"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2024-01-01 00:00:00.000000

WHY write migrations manually vs autogenerate?
  autogenerate is great for simple changes (add column, add table).
  But it can't detect everything:
    - Custom DB functions (gen_random_uuid)
    - Some index configurations
    - Data migrations (moving data between columns)
  
  Senior engineers always REVIEW autogenerated migrations before running them.
  Never blindly trust autogenerate in production.

Interview question: "What is a data migration vs a schema migration?"
  Schema migration: changes the structure (add column, rename table)
  Data migration: moves or transforms data (backfill a new column)
  You run schema first, then data, in separate transactions.
  Never do both in one migration — if it fails halfway, rollback is complex.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Apply this migration — create all tables.

    WHY this order?
      Foreign key constraints require the REFERENCED table to exist first.
      users must be created before interview_sessions (which references users.id).
      This is called "topological ordering" of the dependency graph.
    """

    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('hashed_password', sa.String(60), nullable=False),
        sa.Column('full_name', sa.String(100), nullable=False),
        sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), server_default='user', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_index('ix_users_email', 'users', ['email'])
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'])

    # ── interview_sessions ───────────────────────────────────────────────────
    op.create_table(
        'interview_sessions',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('topic', sa.String(50), nullable=False),
        sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty_enum'), server_default='medium', nullable=False),
        sa.Column('status', sa.Enum('active', 'completed', 'abandoned', name='session_status_enum'), server_default='active', nullable=False),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_interview_sessions_user_id', 'interview_sessions', ['user_id'])
    op.create_index('ix_interview_sessions_status', 'interview_sessions', ['status'])
    op.create_index('ix_sessions_user_topic_status', 'interview_sessions', ['user_id', 'topic', 'status'])

    # ── session_questions ────────────────────────────────────────────────────
    op.create_table(
        'session_questions',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('ideal_answer', sa.Text(), nullable=False),
        sa.Column('skill_topic', sa.String(50), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_session_questions_session_id', 'session_questions', ['session_id'])

    # ── submissions ──────────────────────────────────────────────────────────
    op.create_table(
        'submissions',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('answer_text', sa.Text(), nullable=False),
        sa.Column('similarity_score', sa.Float(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('ai_feedback', sa.Text(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['question_id'], ['session_questions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_submissions_question_id', 'submissions', ['question_id'])

    # ── skill_assessments ────────────────────────────────────────────────────
    op.create_table(
        'skill_assessments',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('skill_topic', sa.String(50), nullable=False),
        sa.Column('proficiency_score', sa.Float(), server_default='0.0', nullable=False),
        sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_skill_assessments_user_topic', 'skill_assessments', ['user_id', 'skill_topic'], unique=True)

    # ── roadmap_items ────────────────────────────────────────────────────────
    op.create_table(
        'roadmap_items',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('skill_topic', sa.String(50), nullable=False),
        sa.Column('resource_title', sa.String(255), nullable=False),
        sa.Column('resource_url', sa.String(512), nullable=False),
        sa.Column('resource_type', sa.String(50), nullable=False),
        sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
        sa.Column('completed', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_roadmap_user_priority', 'roadmap_items', ['user_id', 'priority'])


def downgrade() -> None:
    """
    Reverse this migration — drop all tables.

    WHY implement downgrade?
      If a migration causes production issues, you can roll back:
        alembic downgrade -1   (go back one step)
        alembic downgrade base (go all the way back)

      The order is reverse of upgrade — drop dependent tables first,
      then the tables they depend on.

      Interview question: "How do you roll back a bad database migration?"
    """
    op.drop_table('roadmap_items')
    op.drop_table('skill_assessments')
    op.drop_table('submissions')
    op.drop_table('session_questions')
    op.drop_table('interview_sessions')
    op.drop_table('users')

    # Drop custom enum types — Postgres keeps them even after table drop
    op.execute("DROP TYPE IF EXISTS user_role_enum")
    op.execute("DROP TYPE IF EXISTS difficulty_enum")
    op.execute("DROP TYPE IF EXISTS session_status_enum")
