"""
api/v1/endpoints/roadmap.py — Skill assessments and learning roadmap

This endpoint demonstrates the cache-aside pattern in a real FastAPI endpoint.
"""

import uuid
from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.dependencies import get_current_user
from app.db.redis import get_redis_dep
from app.db.session import get_db
from app.models.submission import RoadmapItem, SkillAssessment
from app.models.user import User
from app.schemas.roadmap import RoadmapItemResponse, RoadmapItemUpdate, SkillAssessmentResponse
from app.services.cache_service import CacheService
from app.services.recommendation_service import RecommendationService

router = APIRouter()


@router.get("/skills", response_model=list[SkillAssessmentResponse])
async def get_skill_assessments(
    current_user: Annotated[User, Depends(get_current_user)],
    db: AsyncSession = Depends(get_db),
    redis=Depends(get_redis_dep),
) -> list[SkillAssessmentResponse]:
    """
    Get the current user's skill proficiency across all topics.

    Cache-aside pattern implementation:
      1. Try Redis first
      2. On miss: query Postgres, store in Redis
      3. Return data from whichever source provided it

    The calling code doesn't know or care whether data came from cache or DB.
    """
    cache = CacheService(redis)

    # ── Step 1: Check cache ────────────────────────────────────────────────────
    cached = await cache.get_skill_assessments(current_user.id)
    if cached is not None:
        # Cache HIT — return immediately without touching Postgres
        # At scale: 95%+ of dashboard loads hit cache, only 5% hit Postgres
        return [SkillAssessmentResponse(**item) for item in cached]

    # ── Step 2: Cache MISS — query Postgres ───────────────────────────────────
    result = await db.execute(
        select(SkillAssessment)
        .where(SkillAssessment.user_id == current_user.id)
        .order_by(SkillAssessment.proficiency_score.desc())
    )
    assessments = result.scalars().all()

    # ── Step 3: Serialize and populate the cache ──────────────────────────────
    # WHY serialize to dict before caching?
    #   SQLAlchemy ORM objects can't be JSON-serialized directly.
    #   We convert to Pydantic schema first (which handles UUID → str, datetime → str)
    #   then to dict for Redis storage.
    serializable = [
        SkillAssessmentResponse.model_validate(a).model_dump(mode="json")
        for a in assessments
    ]
    await cache.set_skill_assessments(current_user.id, serializable)

    return [SkillAssessmentResponse.model_validate(a) for a in assessments]


@router.get("/roadmap", response_model=list[RoadmapItemResponse])
async def get_roadmap(
    current_user: Annotated[User, Depends(get_current_user)],
    db: AsyncSession = Depends(get_db),
    redis=Depends(get_redis_dep),
) -> list[RoadmapItemResponse]:
    """
    Get the user's personalized learning roadmap.

    Roadmap items are generated by the ML recommender service and cached
    aggressively (1 hour) because they're expensive to compute.
    """
    cache = CacheService(redis)

    items = await RecommendationService(db=db, cache=cache).get_or_generate_roadmap(
        current_user.id
    )
    return [RoadmapItemResponse(**item) for item in items]


@router.patch("/roadmap/{item_id}", response_model=RoadmapItemResponse)
async def update_roadmap_item(
    item_id: uuid.UUID,
    update: RoadmapItemUpdate,
    current_user: Annotated[User, Depends(get_current_user)],
    db: AsyncSession = Depends(get_db),
    redis=Depends(get_redis_dep),
) -> RoadmapItemResponse:
    """
    Mark a roadmap item as completed (or uncompleted).

    After a write, we MUST invalidate the cache — the stored data is now stale.
    This is the "write-invalidate" cache consistency strategy.

    WHY not update the cache instead of invalidating it?
      Updating in place requires reading the cached list, modifying one item,
      and writing it back — a read-modify-write. Under concurrent requests,
      two users (or two tabs) could race and one update could overwrite the other.
      Invalidation is simpler and always correct: the next read re-fetches fresh data.

      This is called "cache invalidation on write" — the most common strategy
      for write-heavy data where consistency matters more than cache hit rate.
    """
    from fastapi import HTTPException, status

    item = await db.get(RoadmapItem, item_id)

    if item is None or item.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Item not found")

    item.completed = update.completed
    await db.flush()

    # ── Cache invalidation ─────────────────────────────────────────────────────
    # The cached roadmap for this user is now stale — delete it.
    # Next GET /roadmap will re-query Postgres and re-populate cache.
    cache = CacheService(redis)
    await cache.invalidate_roadmap(current_user.id)

    return RoadmapItemResponse.model_validate(item)
